name: presence_app
description: Application de gestion de prÃ©sence avec scanner QR

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  mobile_scanner: ^3.5.5
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  fl_chart: ^0.68.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true